package com.redhat.lightblue.migrator;

import java.util.Date;

public class MigrationJob {

    public static final String STATE_AVAILABLE="available";
    public static final String STATE_ACTIVE="active";
    public static final String STATE_COMPLETED="completed";
    public static final String STATE_FAILED="failed";

    public static class ConsistencyChecker {
        /**
         * Beginning of job range, date, id, etc.
         */
        private String jobRangeBegin;
        
        /**
         * End of job range, date, id, etc.
         */
        private String jobRangeEnd;

        private String configurationName;

        public String getConfigurationName() {
            return configurationName;
        }
        
        public void setConfigurationName(String s) {
            configurationName=s;
        }

        public String getJobRangeBegin() {
            return jobRangeBegin;
        }
        
        public void setJobRangeBegin(String s) {
            jobRangeBegin=s;
        }
        
        public String getJobRangeEnd() {
            return jobRangeEnd;
        }
        
        public void setJobRangeEnd(String s) {
            jobRangeEnd=s;
        }
        
    }
    
    /**
     * The migration job id
     */
    private String _id;

    private String configurationName;

    /**
     * Date job is scheduled to run
     */
    private Date scheduledDate;

    /**
     * A back-end specific query to retrieve documents that will be migrated by this job
     */
    private String query;

    /**
     * available, processing, complete, failed
     */
    private String status;

    /**
     * Set if generated by consistency checker
     */
    private boolean generated;

    private ConsistencyChecker consistencyChecker;
    

    public String get_id() {
        return _id;
    }

    public void set_id(String s) {
        _id=s;
    }

    public String getConfigurationName() {
        return configurationName;
    }

    public void setConfigurationName(String s) {
        configurationName=s;
    }

    public Date getScheduledDate() {
        return scheduledDate;
    }

    public void setScheduledDate(Date d) {
        scheduledDate=d;
    }

    public String getQuery() {
        return query;
    }

    public void setQuery(String s) {
        query=s;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String s) {
        status=s;
    }

    public boolean isGenerated() {
        return generated;
    }

    public void setGenerated(boolean s) {
        generated=s;
    }

    public ConsistencyChecker getConsistencyChecker() {
        return consistencyChecker;
    }

    public void setConsistencyChecker(ConsistencyChecker c) {
        consistencyChecker=c;
    }
}
